"""create issues tables.

Revision ID: 7875d22715b8
Revises: 
Create Date: 2026-05-19 11:52:02.135679+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers used by Alembic.
revision: str = '7875d22715b8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration.

    Alembic places table creation or schema changes inside this function.
    Running `alembic upgrade head` executes this function.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('author_association', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('comment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comments_id'), 'issue_comments', ['id'], unique=False)
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_issue_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped_label', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('split', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_github_issue_id'), 'issues', ['github_issue_id'], unique=True)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_mapped_label'), 'issues', ['mapped_label'], unique=False)
    op.create_index(op.f('ix_issues_repo_name'), 'issues', ['repo_name'], unique=False)
    op.create_index(op.f('ix_issues_split'), 'issues', ['split'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration.

    Alembic places reverse operations inside this function.
    Running `alembic downgrade -1` executes this function.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_split'), table_name='issues')
    op.drop_index(op.f('ix_issues_repo_name'), table_name='issues')
    op.drop_index(op.f('ix_issues_mapped_label'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_github_issue_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_index(op.f('ix_issue_comments_id'), table_name='issue_comments')
    op.drop_table('issue_comments')
    # ### end Alembic commands ###