"""make normalized email nullable.

Revision ID: c9f5b350d235
Revises: ef80b467ae51
Create Date: 2026-05-21 11:44:43.396849+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Revision identifiers used by Alembic.
revision: str = 'c9f5b350d235'
down_revision: str | None = 'ef80b467ae51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration.

    Alembic places table creation or schema changes inside this function.
    Running `alembic upgrade head` executes this function.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'normalized_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration.

    Alembic places reverse operations inside this function.
    Running `alembic downgrade -1` executes this function.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'normalized_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###